# -*- coding: utf-8 -*-
"""Spotify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jeD1pjGfgQfLMyG5_alO18EXJdKEPrK8
"""

#CIS 545 FINAL PROJECT : SPOTIFY

"""hello friends

"""

